// Imported by the approved isolated V2 harness; never uses real credentials.
import assert from 'node:assert/strict';
export async function checkModelSettings({page,report,shot,pick,url}){
 const snapshot=()=>page.evaluate(async()=>await(await fetch('/api/model-settings')).json());
 await page.getByRole('button',{name:'新建会话',exact:true}).first().click();await pick('选择绑定事项','V2 模拟董事会议案');
 await page.getByRole('textbox',{name:'事项与会话名称',exact:true}).fill('另一个会话 · 路由回归');await page.getByRole('button',{name:'创建会话',exact:true}).click();
 await page.getByRole('heading',{name:'另一个会话 · 路由回归',exact:true}).waitFor();
 await page.locator('.session-item').filter({hasText:'重命名后的披露会话'}).click();await page.getByRole('heading',{name:'重命名后的披露会话',exact:true}).waitFor();
 const nav=()=>page.getByRole('navigation',{name:'主导航'}).getByRole('button').filter({hasText:'模型设置'}).click();
 await nav();await page.getByRole('heading',{name:'模型与供应商',exact:true}).waitFor();
 const brand=await page.locator('.sidebar-subtitle').evaluate(e=>{const r=document.createRange();r.selectNodeContents(e);return{lines:r.getClientRects().length,text:e.textContent,right:r.getBoundingClientRect().right,containerRight:e.getBoundingClientRect().right};});
 assert.equal(brand.text,'DISCLOSURE WORKSPACE');assert.equal(brand.lines,1);assert.ok(brand.right<=brand.containerRight+1);report.checks.push('sidebar_english_one_line_and_fits');
 const initial=await snapshot();
 await page.getByRole('button',{name:'展开 fixture-a',exact:true}).focus();await page.keyboard.press('Enter');
 await page.getByRole('button',{name:'编辑模型 本地接口样例 A',exact:true}).waitFor();
 await page.getByRole('button',{name:'收起 fixture-a',exact:true}).click();assert.equal(await page.getByRole('button',{name:'编辑模型 本地接口样例 A',exact:true}).count(),0);
 const registeredCount=await page.locator('.provider-panel').count();await shot('desktop-provider-overview');await page.getByRole('button',{name:/^添加其他供应商（\d+）$/}).click();assert.ok(await page.locator('.provider-panel').count()>registeredCount);assert.equal(await page.getByRole('combobox',{name:'添加其他供应商',exact:true}).count(),0);await page.getByRole('button',{name:'隐藏未配置供应商',exact:true}).click();assert.equal(await page.locator('.provider-panel').count(),registeredCount);report.checks.push('provider_catalog_expands_inline_list_and_hides_unregistered');
 await page.getByRole('button',{name:'刷新模型目录',exact:true}).click();await page.getByText('模型目录已刷新。',{exact:true}).waitFor();await page.locator('.model-advanced-settings>summary').click();
 await page.getByRole('button',{name:'添加模型',exact:true}).click();await page.getByRole('textbox',{name:'模型显示名称',exact:true}).fill('取消添加不应保存');
 await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
 assert.deepEqual((await snapshot()).models,initial.models);report.checks.push('provider_keyboard_collapse_catalog_and_cancel_add');
 await page.getByRole('button',{name:'添加模型',exact:true}).click();
 await page.getByRole('combobox',{name:'模型供应商',exact:true}).fill('自定义兼容接口');
 await page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden)').getByTitle('自定义兼容接口',{exact:true}).click();
 await page.getByRole('textbox',{name:'模型显示名称',exact:true}).fill('Luna 配置样例');
 await page.getByRole('textbox',{name:'模型 ID',exact:true}).fill('fixture-settings');
 await page.getByRole('textbox',{name:'模型接口地址',exact:true}).fill(url+'/fixture/v1');
 await pick('模型支持档位','max');await page.keyboard.press('Escape');await pick('模型推理档位','max');
 await page.getByRole('button',{name:'保存模型配置',exact:true}).click();
 const row=page.locator('.model-profile-row').filter({hasText:'Luna 配置样例'}),group=page.locator('.provider-panel').filter({has:row});
 await group.getByText('需要保存 API Key',{exact:true}).waitFor();assert.equal(await row.getByRole('button',{name:'测试连接 Luna 配置样例',exact:true}).isEnabled(),false);
 assert.equal(await row.getByRole('button',{name:'设为默认模型 Luna 配置样例',exact:true}).isEnabled(),false);
 report.checks.push('settings_catalog_custom_model_max_and_unconfigured');
 await group.getByLabel('模型 API Key Luna 配置样例',{exact:true}).fill('PUBLIC-SYNTHETIC-KEY-NOT-A-SECRET');
 await group.getByRole('button',{name:'保存 API Key Luna 配置样例',exact:true}).click();await page.getByText('API Key 已保存到系统凭据库。',{exact:true}).waitFor();assert.equal(await group.getByLabel('模型 API Key Luna 配置样例',{exact:true}).inputValue(),'');report.checks.push('inline_api_key_save_and_clear_field');
 await row.getByRole('button',{name:'测试连接 Luna 配置样例',exact:true}).click();await page.getByText('Luna 配置样例 · max 连接测试通过。',{exact:true}).waitFor();
 const wire=await page.evaluate(async()=>await(await fetch('/fixture/observations')).json());
 assert.deepEqual(wire.filter(row=>row.kind==='connection_probe'),[{kind:'connection_probe',model:'fixture-settings',reasoning_effort:'max',message_count:2,tools:0,customer_context:false}]);
 const state=await snapshot();assert.ok(!JSON.stringify(state).includes('PUBLIC-SYNTHETIC-KEY'));assert.equal(state.models.find(r=>r.id==='fixture-settings').configured,true);
 report.checks.push('settings_fake_vault_no_key_echo','real_pi_probe_max_wire_and_no_customer_context');
 await row.getByRole('button',{name:'编辑模型 Luna 配置样例',exact:true}).click();await page.getByRole('textbox',{name:'模型显示名称',exact:true}).fill('取消编辑不应保存');await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
 assert.equal((await snapshot()).models.find(r=>r.id==='fixture-settings').label,'Luna 配置样例');
 await page.getByRole('button',{name:'按工作环节设置',exact:true}).click();await pick('所有节点默认模型','Luna 配置样例 · max');await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
 await row.getByRole('checkbox',{name:'在聊天栏显示 Luna 配置样例',exact:true}).click();
  await page.waitForFunction(async()=>!(await(await fetch('/api/model-settings')).json()).models.find(m=>m.id==='fixture-settings').visible);
 assert.deepEqual((await snapshot()).routes,state.routes);
 await row.getByRole('checkbox',{name:'在聊天栏显示 Luna 配置样例',exact:true}).click();
 await page.waitForFunction(async()=>(await(await fetch('/api/model-settings')).json()).models.find(m=>m.id==='fixture-settings').visible);
 report.checks.push('edit_and_route_cancel_preserve_state_visibility_does_not_commit_routes');
 await page.getByRole('button',{name:'按工作环节设置',exact:true}).click();await pick('披露判断模型','本地接口样例 B');
 await page.getByRole('button',{name:'保存默认选择',exact:true}).click();await page.getByText('工作环节默认模型已保存，下一次准备执行时生效。',{exact:true}).waitFor();
 assert.equal(await row.getByRole('checkbox',{name:'在聊天栏显示 Luna 配置样例',exact:true}).isChecked(),true);await row.getByRole('checkbox',{name:'在聊天栏显示 Luna 配置样例',exact:true}).click();await page.waitForFunction(async()=>!(await(await fetch('/api/model-settings')).json()).models.find(m=>m.id==='fixture-settings').visible);await row.getByRole('button',{name:'设为默认模型 Luna 配置样例',exact:true}).click();await page.getByText('Luna 配置样例 · max 已设为默认模型，下一次准备执行时生效。',{exact:true}).waitFor();
 const chosen=await snapshot();assert.equal(chosen.routes.default,chosen.models.find(m=>m.id==='fixture-settings').key);assert.equal(chosen.routes.assessment,'fixture-b');assert.equal(chosen.models.find(m=>m.id==='fixture-settings').visible,true);report.checks.push('default_selection_makes_model_visible_in_chat');
 assert.equal(await row.getByRole('button',{name:'设为默认模型 Luna 配置样例',exact:true}).getAttribute('aria-pressed'),'true');
 assert.equal(await group.getByRole('checkbox',{name:/启用供应商/}).isEnabled(),false);
 await page.getByRole('button',{name:'按工作环节设置',exact:true}).click();assert.ok((await page.locator('.ant-select').filter({has:page.getByRole('combobox',{name:'披露判断模型',exact:true})}).innerText()).includes('本地接口样例 B'));await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
 report.checks.push('default_radio_preserves_saved_workflow_override_and_routed_disable_guard');
 await shot('desktop-model-settings');await page.setViewportSize({width:390,height:844});await shot('narrow-model-settings');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));
 await row.getByRole('button',{name:'编辑模型 Luna 配置样例',exact:true}).click();await page.getByRole('dialog',{name:'编辑模型配置',exact:true}).waitFor();await page.waitForFunction(()=>{const d=document.querySelector('.ant-modal');return d&&getComputedStyle(d).transform==='none'&&getComputedStyle(d).opacity==='1';});const actionBounds=await page.getByRole('button',{name:'保存模型配置',exact:true}).boundingBox();assert.ok(actionBounds&&actionBounds.y>=0&&actionBounds.y+actionBounds.height<=844);await shot('narrow-model-edit');report.checks.push('narrow_model_dialog_actions_visible_with_scrollable_fields');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2));await page.getByRole('dialog').getByRole('button',{name:'取消',exact:true}).click();
 await page.setViewportSize({width:1440,height:1000});
 await page.getByRole('button',{name:'返回对话',exact:true}).click();await page.getByRole('heading',{name:'重命名后的披露会话',exact:true}).waitFor();
 assert.ok((await page.locator('.ant-select').filter({has:page.getByRole('combobox',{name:'选择本轮模型',exact:true})}).innerText()).includes('Luna 配置样例 · max'));
 report.checks.push('settings_default_route_back_to_same_session','settings_desktop_and_narrow_layout');
 await nav();await page.getByRole('button',{name:'展开 自定义兼容接口',exact:true}).click();
 await group.getByRole('button',{name:'移除授权',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'移除授权',exact:true}).click();
 await group.getByText('需要保存 API Key',{exact:true}).waitFor();assert.equal(await row.getByRole('button',{name:'测试连接 Luna 配置样例',exact:true}).isEnabled(),false);
 assert.ok((await row.innerText()).includes('尚未测试连接'));report.checks.push('settings_remove_credential_clears_connection_check');
}
