import {useEffect,useState} from 'react';
import {Alert,Button,Checkbox,Empty,Input,Modal,Select,Space,Table,Tag,Tooltip} from 'antd';
import {api} from '../api';
import LibraryFileActions from './LibraryFileActions';
type Classification={tags:string[];forms:string[];status:string;requires_pi?:boolean;review_reason?:string;manual_expired?:boolean;evidence?:{quote?:string;page?:number}};
type Facet={id:string;label:string;count:number;common?:boolean};
type Row={id:string;title:string;published_at:string;announcement_number?:string;meeting_date?:string;meeting?:{organ:string;term?:number;year?:number;sequence?:number;basis:string;meeting_type:string};relation:string;related_ids:string[];deleted_at?:string;pages?:{page:number;text:string}[];anchors?:Record<string,string>;classification?:Classification;classification_override?:{tags:string[];forms:string[]}|null};
type Snapshot={classification_run?:{id:string;status:string;reason:string}|null;items:Row[];fingerprint:string;company_name:string;updated_at?:string;coverage:{from?:string;through?:string;complete:boolean;note?:string};tag_options:Facet[];form_options:Facet[];matched_total:number;related_options:{id:string;title:string}[]};
const classificationLabel=(c?:Classification)=>c?.status==='manual'?'人工校正':c?.status==='pi_reviewed'?'Pi已复判':c?.status==='needs_human'?'待人工识别':'候选 · 待Pi复判';
export default function AnnouncementSchedule({board,company,onAssist}:{board:string;company:string;onAssist?:(message:string)=>void}){
 const [snapshot,setSnapshot]=useState<Snapshot>(),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[reload,setReload]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState<string[]>([]),[detail,setDetail]=useState<Row>(),[deleted,setDeleted]=useState(false),[edit,setEdit]=useState<Row>(),[reason,setReason]=useState(''),[coverage,setCoverage]=useState<Snapshot['coverage']>();
 const refresh=()=>{setSelected([]);setReload(x=>x+1);};
 const [tag,setTag]=useState(''),[form,setForm]=useState(''),[more,setMore]=useState(false),[page,setPage]=useState(1),[classificationChanged,setClassificationChanged]=useState(false);
 const chooseTag=(value:string)=>{setTag(value);setForm('');setPage(1);};
 useEffect(()=>{let active=true;setSelected([]);setPage(1);if(!company)return;setBusy(true);setError('');api<Snapshot>(`/announcement-schedule?${new URLSearchParams({board,company,q:search,deleted:String(deleted),tag,form})}`).then(r=>{if(active)setSnapshot(r);}).catch(e=>{if(active){setError(e.message);setSnapshot(undefined);}}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};},[board,company,search,reload,deleted,tag,form]);
 const [reviewNotice,setReviewNotice]=useState('');
 const reviewRun=snapshot?.classification_run;
 useEffect(()=>{if(!reviewRun||!['accepted','running','cancelling'].includes(reviewRun.status))return;const timer=setTimeout(()=>setReload(n=>n+1),5000);return()=>clearTimeout(timer);},[reviewRun,reload]);
 const startReview=()=>action(async()=>{const result=await api<{status:string;reason?:string}>('/announcement-schedule/review','POST',{board,company});setReviewNotice(result.reason||'已提交Pi复判，沿用模型设置中的默认模型。');refresh();});
 const correctionOptions=snapshot?.related_options||[];
 const saveCorrection=()=>action(async()=>{
   const changes:Record<string,unknown>={announcement_number:edit!.announcement_number,meeting_date:edit!.meeting_date,meeting:edit!.meeting,related_ids:edit!.related_ids||[],relation:edit!.relation};
   if(classificationChanged)changes.classification_override=edit!.classification_override===null?null:{tags:edit!.classification!.tags,forms:edit!.classification!.forms};
   await api('/announcement-schedule','PATCH',{board,company,id:edit!.id,fingerprint:snapshot!.fingerprint,changes,reason});setEdit(undefined);refresh();
 });
 const action=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 if(!company)return <Empty description="请在顶部选择或登记本公司，历史公告和公告时间表按公司隔离"/>;
 const base=new URLSearchParams({board,company}).toString();
 return <section className="resource-page library-page"><div className="page-heading"><div><span className="page-kicker">ANNOUNCEMENT SCHEDULE</span><h1>公告时间表</h1><p>核对本公司的公告编号、会议届次及前后披露关系。</p></div><Button onClick={refresh}>刷新</Button></div>
 <p className="history-company-title"><strong>{snapshot?.company_name}</strong> · {company}</p><Alert className="history-coverage-alert" type={snapshot?.coverage.complete?'success':'info'} message={snapshot?.coverage.complete?`已确认覆盖 ${snapshot.coverage.from} 至 ${snapshot.coverage.through}；范围外仍需补核`:'历史覆盖尚未确认，核对仅限已登记公告'} description={snapshot?.coverage.note?<details><summary>查看说明</summary><p>{snapshot.coverage.note}</p></details>:undefined}/>
 <div className="library-toolbar history-toolbar"><Input.Search aria-label="搜索历史公告" placeholder="标题、公告编号或正文关键词" value={query} onChange={e=>setQuery(e.target.value)} onSearch={()=>setSearch(query)} style={{maxWidth:440}}/><Space className="history-toolbar-actions" size={8}><LibraryFileActions board={board} collection="history" company={company} selected={selected} onSaved={refresh} onAssist={onAssist}/><Button onClick={()=>setCoverage({...snapshot?.coverage,complete:snapshot?.coverage.complete||false})}>核对覆盖范围</Button><Checkbox checked={deleted} onChange={e=>setDeleted(e.target.checked)}>显示已删除</Checkbox></Space></div>
 {error&&<Alert type="error" message={error}/>}
 <div className="announcement-review-bar"><span>规则候选未达到经校准的99%门槛，须由Pi结合原文复判。{reviewRun?'最近复判：'+({accepted:'已接收',running:'执行中',completed:'已完成',failed:'失败',incomplete:'未完成',cancelled:'已暂停',interrupted:'已中断',waiting_user:'待人工识别'}[reviewRun.status]||reviewRun.status):''}</span><Button disabled={busy||!!reviewRun&&['accepted','running','cancelling'].includes(reviewRun.status)} onClick={startReview}>Pi复判待识别</Button>{reviewRun&&['accepted','running'].includes(reviewRun.status)&&<Button onClick={()=>action(async()=>{await api('/chat/runs/'+reviewRun.id+'/cancel','POST',{});refresh();})}>暂停复判</Button>}</div>
 {reviewNotice&&<p role="status" className="muted">{reviewNotice}</p>}
 <div className="announcement-filters" aria-label="公告分类筛选">
 <div className="announcement-tag-row" role="group" aria-label="公告标签">
 <button type="button" className="announcement-filter" aria-pressed={!tag} disabled={busy} onClick={()=>chooseTag('')}>全部 <small>{snapshot?.matched_total??0}</small></button>
 {snapshot?.tag_options?.filter(t=>more||t.common||t.id===tag).map(t=><button type="button" key={t.id} className="announcement-filter" aria-pressed={tag===t.id} disabled={busy||(!t.count&&tag!==t.id)} onClick={()=>chooseTag(tag===t.id?'':t.id)}>{t.label} <small>{t.count}</small></button>)}
 <button type="button" className="announcement-filter-toggle" aria-expanded={more} onClick={()=>setMore(!more)}>{more?'收起标签':'更多标签'}</button>
 </div>
 {tag&&<div className="announcement-tag-row" role="group" aria-label="文件细分"><span>文件细分</span><button type="button" className="announcement-filter" aria-pressed={!form} disabled={busy} onClick={()=>setForm('')}>全部</button>{snapshot?.form_options?.filter(f=>f.count>0||f.id===form).map(f=><button type="button" key={f.id} className="announcement-filter" aria-pressed={form===f.id} disabled={busy} onClick={()=>{setForm(form===f.id?'':f.id);setPage(1);}}>{f.label} <small>{f.count}</small></button>)}</div>}
 </div>
 <Table<Row> className="compact-announcement-table" tableLayout="fixed" rowKey="id" size="small" dataSource={snapshot?.items||[]} loading={busy} rowSelection={{selectedRowKeys:selected,onChange:keys=>setSelected(keys.map(String)),getCheckboxProps:r=>({disabled:!!r.deleted_at})}} scroll={{x:1300}} pagination={{current:page,onChange:setPage,pageSize:20,showSizeChanger:false,showTotal:n=>`共 ${n} 份公告`}} columns={[
 {title:'发布日期',dataIndex:'published_at',width:120,render:v=><span style={{whiteSpace:'nowrap'}}>{v}</span>},{title:'公告编号',dataIndex:'announcement_number',width:138,render:v=><span className="announcement-number">{v||'未识别'}</span>},
 {title:'公告标题',dataIndex:'title',render:(v,r)=><span className="announcement-title"><Tooltip title={v}><strong>{v}</strong></Tooltip>{r.deleted_at&&<Tag>已删除</Tag>}</span>},
 {title:'标签',width:145,render:(_,r)=><Tooltip title={<>{r.classification?.tags.map(id=>snapshot?.tag_options.find(t=>t.id===id)?.label||id).join('、')} · {classificationLabel(r.classification)}{r.classification?.manual_expired?'；正文版本已变化，旧分类校正失效':''}</>}><button type="button" className="announcement-row-tag" disabled={busy} onClick={()=>chooseTag(r.classification?.tags[0]||'unclassified')}>{snapshot?.tag_options.find(t=>t.id===r.classification?.tags[0])?.label||'待分类'}{r.classification?.requires_pi?' · 待复判':''}{(r.classification?.tags.length||0)>1?` +${r.classification!.tags.length-1}`:''}</button></Tooltip>},
 {title:'会议届次 / 年度 / 序号',key:'meeting',width:210,render:(_:unknown,r:Row)=><span className="announcement-meeting">{r.meeting?`${r.meeting.organ} · ${r.meeting.term?`第${r.meeting.term}届`:r.meeting.year||''} · ${r.meeting.sequence?`第${r.meeting.sequence}次`:r.meeting.meeting_type}`:'—'}</span>},{title:'会议日期',dataIndex:'meeting_date',width:120,render:(v:string)=><span className="announcement-meeting-date">{v||'待核 / 不适用'}</span>},
 {title:'操作',width:118,fixed:'right',render:(_,r)=><span className="compact-row-actions" role="group" aria-label={`公告 ${r.title} 的操作`}>{r.deleted_at?<Button type="link" className="compact-table-action" onClick={()=>action(async()=>{await api('/announcement-schedule/restore','POST',{board,company,id:r.id,fingerprint:snapshot!.fingerprint});refresh();})}>恢复</Button>:<><Button type="link" className="compact-table-action" onClick={()=>action(async()=>setDetail({...await api<Row>(`/announcements/${r.id}?${base}`),classification:r.classification}))}>查看</Button><span className="compact-action-divider" aria-hidden="true">·</span><Button type="link" className="compact-table-action" onClick={()=>{setEdit({...r});setReason('');setClassificationChanged(false);}}>校正</Button></>}</span>}
 ]}/>
 <Modal title={detail?.title} open={!!detail} width={920} footer={null} onCancel={()=>setDetail(undefined)}><p>标签：{detail?.classification?.tags.map(id=>snapshot?.tag_options.find(t=>t.id===id)?.label||id).join('、')} · {classificationLabel(detail?.classification)}</p><p>文件细分：{detail?.classification?.forms.map(id=>snapshot?.form_options.find(t=>t.id===id)?.label||id).join('、')}</p>{detail?.classification?.evidence?.quote&&<details><summary>分类依据{detail.classification.evidence.page?`（第 ${detail.classification.evidence.page} 页）`:''}</summary><p className="preserve">{detail.classification.evidence.quote}</p></details>}<p><a href={`/api/announcements/${detail?.id}/original?${base}`} target="_blank" rel="noreferrer">打开已登记原件</a></p><p>关联公告：{detail?.related_ids?.map(id=>correctionOptions.find(r=>r.id===id)?.title||id).join('；')||'未登记'}</p>{detail?.pages?.map(p=><details key={p.page} open={p.page===1}><summary>页 / 结构单元 {p.page}</summary><pre className="preserve">{p.text}</pre></details>)}</Modal>
 <Modal title="校正提取字段" open={!!edit} confirmLoading={busy} onCancel={()=>setEdit(undefined)} onOk={saveCorrection}><p>只校正结构化记录，原公告内容保留。</p><Input aria-label="校正公告编号" placeholder="公告编号" value={edit?.announcement_number||''} onChange={e=>setEdit(v=>v&&({...v,announcement_number:e.target.value}))}/><Input aria-label="校正会议日期" type="date" value={edit?.meeting_date||''} onChange={e=>setEdit(v=>v&&({...v,meeting_date:e.target.value}))} style={{margin:'12px 0'}}/>{edit?.meeting&&<Space wrap>{(['term','year','sequence'] as const).map(key=><Input key={key} aria-label={{term:'届次',year:'年度',sequence:'会议序号'}[key]} type="number" min={1} placeholder={{term:'届次',year:'年度',sequence:'会议序号'}[key]} value={edit.meeting?.[key]||''} onChange={e=>setEdit(v=>v&&({...v,meeting:{...v.meeting!,[key]:e.target.value?Number(e.target.value):undefined}}))}/>)}</Space>}<Select mode="multiple" aria-label="关联前序公告" placeholder="关联本公司前序公告" style={{width:'100%',marginTop:12}} value={edit?.related_ids||[]} options={correctionOptions.filter(r=>r.id!==edit?.id).map(r=>({value:r.id,label:r.title}))} onChange={ids=>setEdit(v=>v&&({...v,related_ids:ids}))}/><Select aria-label="公告关系" style={{width:'100%',marginTop:12}} value={edit?.relation} options={[{value:'new',label:'首次 / 独立公告'},{value:'progress',label:'进展'},{value:'postponed',label:'延期'},{value:'corrected',label:'更正 / 修订'},{value:'cancelled',label:'取消 / 终止'}]} onChange={relation=>setEdit(v=>v&&({...v,relation}))}/><label className="form-label">公告标签</label><Select mode="multiple" aria-label="校正公告标签" style={{width:'100%'}} value={edit?.classification?.tags||[]} options={snapshot?.tag_options?.map(t=>({value:t.id,label:t.label}))} onChange={tags=>{setClassificationChanged(true);setEdit(v=>v&&({...v,classification_override:undefined,classification:{...v.classification!,tags}}));}}/><label className="form-label">文件细分</label><Select mode="multiple" aria-label="校正文件细分" style={{width:'100%'}} value={edit?.classification?.forms||[]} options={snapshot?.form_options?.map(t=>({value:t.id,label:t.label}))} onChange={forms=>{setClassificationChanged(true);setEdit(v=>v&&({...v,classification_override:undefined,classification:{...v.classification!,forms}}));}}/><p className="muted">当前分类：{classificationLabel(edit?.classification)}。分类校正绑定本份正文版本。</p><Button type="link" onClick={()=>{setClassificationChanged(true);setEdit(v=>v&&({...v,classification_override:null}));}}>恢复自动分类（保存后生效）</Button>{classificationChanged&&edit?.classification_override===null&&<p>保存时将移除人工分类，按当前正文重新分类。</p>}<Input.TextArea aria-label="校正原因" placeholder="校正原因与原文位置" value={reason} onChange={e=>setReason(e.target.value)} style={{marginTop:12}}/>{error&&<Alert type="error" message={error}/>}</Modal>
 <Modal title="确认历史覆盖范围" open={!!coverage} confirmLoading={busy} onCancel={()=>setCoverage(undefined)} onOk={()=>action(async()=>{await api('/announcement-schedule/coverage','POST',{board,company,fingerprint:snapshot!.fingerprint,coverage});setCoverage(undefined);refresh();})}><p>请与官方公告列表核对完整性；下载数量不能证明没有遗漏。</p><Space><Input aria-label="覆盖起始日" type="date" value={coverage?.from||''} onChange={e=>setCoverage(v=>({...v!,from:e.target.value}))}/><Input aria-label="覆盖截止日" type="date" value={coverage?.through||''} onChange={e=>setCoverage(v=>({...v!,through:e.target.value}))}/></Space><p><Checkbox checked={coverage?.complete} onChange={e=>setCoverage(v=>({...v!,complete:e.target.checked}))}>我已核对该期间公告完整性</Checkbox></p><Input aria-label="覆盖说明" value={coverage?.note||''} onChange={e=>setCoverage(v=>({...v!,note:e.target.value}))}/>{error&&<Alert type="error" message={error}/>}</Modal>
 </section>;
}
