import {useEffect,useState} from 'react';
import {Alert,Button,Empty,Input,Modal,Pagination,Select,Space,Spin,Table,Tag,Tooltip} from 'antd';
import {api} from '../api';
import type {Knowledge} from '../types';
import Evidence from './Evidence';
import LibraryFileActions from './LibraryFileActions';
import type {Board} from '../companyWorkspace';

type EvidenceDocument={id:string;role:string;title:string;url:string;published_at?:string;page_count?:number};
type Row={id:string;title:string;article?:string;text?:string;article_count?:number;effective_from?:string;published_at?:string;as_of?:string;source_kind?:string;page_count?:number;verification_status?:string;original_path?:string;document_path?:string;library_board?:string;scope_review_status?:string;company?:string;stock_code?:string;decision_date?:string;decision_number?:string;authority?:string;disposition_type?:string;announcement_kinds?:string[];violation_types?:string[];wrongdoing_summary?:string;regulator_finding?:string;drafting_checks?:string[];admission_status?:string;evidence_complete?:boolean;evidence_documents?:EvidenceDocument[]};
type ProfileSection={id:string;title:string;condition:string;requirement?:string;fields:{prompt:string;table_rows?:string[][]}[]};
type Detail=Knowledge&Row&{articles?:Row[];applicability?:string;normative_sources?:Row[];case_sources?:Row[];sections?:ProfileSection[];semantic_review?:string[];pages?:(number|{page:number;text:string})[];text_completeness?:string};
const collections=[{value:'laws',label:'法规库'},{value:'cases',label:'案例库'},{value:'profiles',label:'模板库'}];
const kinds=[['board_resolution','董事会决议'],['shareholder_notice','股东会通知'],['management_change','人员变动'],['related_transaction','关联交易'],['litigation_arbitration','诉讼仲裁']].map(([value,label])=>({value,label}));
const blacklistKinds=[...kinds,
 {value:'annual_report',label:'年度报告'},{value:'half_year_report',label:'半年度报告'},{value:'quarter_report',label:'季度报告'},
 {value:'performance_forecast',label:'业绩预告'},{value:'fundraising',label:'募集资金'},{value:'major_transaction',label:'重大交易'},
 {value:'share_reduction',label:'股东减持及权益变动'},{value:'refinancing_bond',label:'可转债发行文件'},{value:'refinancing_equity',label:'再融资文件'}];
const violations=[['false_record','虚假记载'],['material_omission','重大遗漏'],['misleading_statement','误导性陈述'],['late_disclosure','迟延披露'],['non_disclosure','未披露'],['inconsistent_data','数据或口径不一致']].map(([value,label])=>({value,label}));
const dispositions=[['administrative_penalty','行政处罚'],['disciplinary_action','交易所纪律处分'],['regulatory_measure','监管措施']].map(([value,label])=>({value,label}));
const labelOf=(options:{value:string;label:string}[],value?:string)=>options.find(x=>x.value===value)?.label||value||'未分类';
const evidenceRoles:Record<string,string>={regulatory_decision:'官方处理决定',affected_announcement:'涉事公告',correction:'更正公告',remediation:'整改文件',follow_up:'后续文件'};
const lawStatus=(value?:string)=>({'detailed_applicability_pending':'适用范围待复核','394_units_390_provisions_reassembled':'正文已重组','193_units_67_complete_articles':'正文已索引'}[value||'']||value||'已登记');
export default function LibraryPage({board,companyCode='',onAssist}:{board:Board;companyCode?:string;onAssist?:(message:string)=>void}){
 const pageSize=20;
 const [selectedIds,setSelectedIds]=useState<string[]>([]);
 const [collection,setCollection]=useState('laws');const [kind,setKind]=useState<string>();const [query,setQuery]=useState('');const [q,setQ]=useState('');const [page,setPage]=useState(1);
 const [rows,setRows]=useState<Row[]>([]);const [total,setTotal]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [retry,setRetry]=useState(0);
 const [caseView,setCaseView]=useState('items');const [caseCounts,setCaseCounts]=useState({admitted:0,candidates:0});
 const [blacklistCounts,setBlacklistCounts]=useState({admitted:0,candidates:0});const [violation,setViolation]=useState<string>();const [disposition,setDisposition]=useState<string>();const [year,setYear]=useState<string>();
 const [selected,setSelected]=useState<Row>();const [detail,setDetail]=useState<Detail>();const [documentPage,setDocumentPage]=useState(1);const [detailError,setDetailError]=useState('');const [detailRetry,setDetailRetry]=useState(0);
 useEffect(()=>{let active=true;setBusy(true);setError('');setRows([]);setSelected(undefined);setSelectedIds([]);
 const params=new URLSearchParams({collection,q,board:board.layer!,company:companyCode,offset:String((page-1)*pageSize),limit:String(pageSize),view:collection==='laws'?'groups':collection==='cases'||collection==='blacklist_cases'?caseView:'items'});if(kind)params.set('kind',kind);if(violation)params.set('violation',violation);if(disposition)params.set('disposition',disposition);if(year)params.set('year',year);
 api<{items:Row[];total:number;case_scope_summary:{admitted:number;candidates:number};blacklist_scope_summary:{admitted:number;candidates:number}}>(`/library/search?${params}`).then(r=>{if(active){setRows(r.items);setTotal(r.total);setCaseCounts(r.case_scope_summary);setBlacklistCounts(r.blacklist_scope_summary);}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setBusy(false);});return()=>{active=false;};
 },[board.layer,companyCode,collection,caseView,kind,violation,disposition,year,q,page,retry]);
 useEffect(()=>{let active=true;setDetail(undefined);setDetailError('');if(!selected)return;
 const suffix=`?board=${board.layer}&company=${companyCode}`+(selected.document_path||selected.source_kind==='official_case'||selected.source_kind==='imported_case_candidate'?`&page=${documentPage}`:'');
 api<Detail>(`/library/items/${encodeURIComponent(selected.id)}${suffix}`).then(d=>{if(active)setDetail(d);}).catch(e=>{if(active)setDetailError(e.message);});return()=>{active=false;};
 },[board.layer,companyCode,selected,documentPage,detailRetry]);
 return <section className="resource-page library-page">
 <div className="page-heading"><div><span className="page-kicker">REFERENCE LIBRARY</span><h1>知识库</h1><p className="muted">核对法源、阅读案例，查看各文种的内容与格式要求。</p></div><Button loading={busy} onClick={()=>setRetry(x=>x+1)}>刷新资料</Button></div>
 <div className="collection-tabs" role="group" aria-label="选择知识库">{collections.map(item=><button key={item.value} className="collection-tab" aria-pressed={collection===item.value||(item.value==='cases'&&collection==='blacklist_cases')} onClick={()=>{setCollection(item.value);setPage(1);setKind(undefined);setViolation(undefined);setDisposition(undefined);setYear(undefined);}}>{item.label}</button>)}</div>
 {(collection==='cases'||collection==='blacklist_cases')&&<div className="case-category" role="group" aria-label="案例分类"><Button type={collection==='cases'?'primary':'default'} onClick={()=>{setCollection('cases');setCaseView('items');setKind(undefined);setViolation(undefined);setDisposition(undefined);setYear(undefined);setPage(1);}}>普通案例</Button><Button type={collection==='blacklist_cases'?'primary':'default'} onClick={()=>{setCollection('blacklist_cases');setCaseView('items');setKind(undefined);setViolation(undefined);setDisposition(undefined);setYear(undefined);setPage(1);}}>违规案例</Button></div>}
 <div className="library-toolbar"><div className="library-filters"><Input.Search aria-label="搜索知识库" placeholder={collection==='blacklist_cases'?'公司、决定编号或违规关键词':'标题、条文或关键词'} value={query} onChange={e=>setQuery(e.target.value)} onSearch={()=>{setQ(query);setPage(1);}} loading={busy} allowClear/><Select aria-label="筛选事项类别" allowClear placeholder="全部事项类别" value={kind} options={collection==='blacklist_cases'?blacklistKinds:kinds} onChange={v=>{setKind(v);setPage(1);}}/>{collection==='blacklist_cases'&&<><Select aria-label="筛选错误类型" allowClear placeholder="全部错误类型" value={violation} options={violations} onChange={v=>{setViolation(v);setPage(1);}}/><Select aria-label="筛选处理性质" allowClear placeholder="全部处理性质" value={disposition} options={dispositions} onChange={v=>{setDisposition(v);setPage(1);}}/><Input aria-label="筛选处理年份" placeholder="处理年份" value={year} maxLength={4} onChange={e=>{setYear(e.target.value.replace(/\D/g,''));setPage(1);}}/></>}</div><LibraryFileActions key={`${board.id}-${collection}`} board={board.layer!} collection={collection} company={companyCode} selected={selectedIds} onSaved={()=>{setSelectedIds([]);setRetry(x=>x+1);}} onAssist={onAssist}/></div>
 <p className="library-scope-note">当前适用{board.fullName}法规与案例；模板包含板块通用版及本公司专用版。{board.layer==='chinext'?'导入规则的缺漏正文已补齐；模板及版式仍待专业复核。':'已分开明确的层级专属条款，并标注共用条文与模板中的层级条件；不代表完整覆盖全部披露事项。'}{collection==='blacklist_cases'?'黑名单案例须核实官方处理决定和违规时点板块；旧规则不能替代当前法源。':'案例须核实官方原件和公告时点层级后接纳。'}</p>
 {collection==='cases'&&<div className="library-toolbar"><Select aria-label="案例接纳状态" value={caseView} style={{minWidth:240}} options={[{value:'items',label:`本层已核实案例（${caseCounts.admitted}）`},{value:'candidates',label:`待核资料（${caseCounts.candidates}）`}]} onChange={value=>{setCaseView(value);setPage(1);}}/><span className="muted">待核资料不计入本层案例覆盖，不可作为任务清单依据。</span></div>}
 {collection==='blacklist_cases'&&<div className="library-toolbar"><Select aria-label="监管案例接纳状态" value={caseView} style={{minWidth:260}} options={[{value:'items',label:`已核实监管案例（${blacklistCounts.admitted}）`},{value:'candidates',label:`待核线索（${blacklistCounts.candidates}）`}]} onChange={value=>{setCaseView(value);setPage(1);}}/><span className="muted">按违规事项收录；问询、立案和自行更正不直接作为已核实监管案例。</span></div>}
 {error&&<Alert type="error" message={error} action={<Button onClick={()=>setRetry(x=>x+1)}>重试</Button>}/>}
 <Table<Row> className="compact-library-table" size="small" rowKey="id" loading={busy} dataSource={rows} rowSelection={collection==='laws'?undefined:{selectedRowKeys:selectedIds,onChange:keys=>setSelectedIds(keys.map(String))}} scroll={{x:collection==='laws'?860:collection==='blacklist_cases'?1100:720}} pagination={{current:page,pageSize,total,showSizeChanger:false,showTotal:n=>`共 ${n} 条`,onChange:setPage}} locale={{emptyText:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="未检索到资料；不能据此推定不存在披露义务"/>}} columns={collection==='laws'?[{title:'法律／法规名称',dataIndex:'title',render:(v:string)=><Tooltip title={v}><span className="record-title law-group-title">{v}</span></Tooltip>},{title:'条款数',dataIndex:'article_count',width:100,render:(v:number)=>`${v||0} 条`},{title:'生效时点',width:130,render:(_:unknown,r:Row)=>r.effective_from||r.as_of||'未登记'},{title:'资料状态',width:180,render:(_:unknown,r:Row)=><span className="status-text">{lawStatus(r.scope_review_status)}</span>},{title:'操作',width:120,render:(_,r:Row)=><Button type="link" className="text-link" onClick={()=>{setDocumentPage(1);setSelected(r);}}>查看法条</Button>}]:collection==='blacklist_cases'?[
 {title:'公司／事项',width:330,render:(_,r)=><Tooltip title={r.title}><span className="record-name"><span className="record-title">{r.company}（{r.stock_code}）· {r.title}</span></span></Tooltip>},{title:'公告类型',width:170,render:(_,r)=><Space size={[2,2]} wrap>{r.announcement_kinds?.map(x=><Tag key={x}>{labelOf(blacklistKinds,x)}</Tag>)}</Space>},{title:'错误类型',width:190,render:(_,r)=><Space size={[2,2]} wrap>{r.violation_types?.map(x=><Tag key={x} color="warning">{labelOf(violations,x)}</Tag>)}</Space>},{title:'处理',width:180,render:(_,r)=><><span>{labelOf(dispositions,r.disposition_type)}</span><div className="record-subtitle">{r.decision_date||'未登记'}</div></>},{title:'证据链',width:110,render:(_,r)=>r.evidence_complete?'已关联':'待补公告'},{title:'操作',width:90,render:(_,r)=><Button type="link" className="text-link" onClick={()=>{setDocumentPage(1);setSelected(r);}}>查看</Button>}]:[
 {title:'资料名称',dataIndex:'title',render:(v,r)=>{const label=r.article?`${v} · ${r.article}`:v;return <Tooltip title={label}><span className="record-name" aria-label={label}><span className="record-title">{v}</span>{r.article&&<span className="record-subtitle">· {r.article}</span>}</span></Tooltip>}},
 {title:'时点',width:130,render:(_,r)=>r.published_at||r.effective_from||r.as_of||'未登记'},
 {title:'资料状态',width:150,render:(_,r)=><span className="status-text">{collection==='profiles'?'待专业验收':r.verification_status==='imported_source_unverified'?'导入待核验':r.scope_review_status==='publication_layer_unverified'?'发布层级待核对':r.verification_status==='legacy_lead_not_profile_evidence'?'历史线索':'已登记'}</span>},
 {title:'操作',width:110,render:(_,r)=><Button type="link" className="text-link" onClick={()=>{setDocumentPage(1);setSelected(r);}}>查看</Button>}
 ]}/>
 <Modal open={!!selected} title={`${board.name} · ${selected?.title||''}`} width={960} footer={null} onCancel={()=>setSelected(undefined)} destroyOnClose className="library-detail-modal">
 {detailError?<Alert type="error" message={detailError} action={<Button onClick={()=>setDetailRetry(x=>x+1)}>重新读取</Button>}/>:!detail?<Spin/>:detail.source_kind==='blacklist_case'?<div className="blacklist-detail"><Alert type={detail.admission_status==='admitted'?'info':'warning'} message={detail.admission_status==='admitted'?'官方处理决定和违规时点板块已核实':'当前为待核线索，不能作为已核实监管案例'}/><h3>{detail.company}（{detail.stock_code}）</h3><p>{labelOf(dispositions,detail.disposition_type)} · {detail.authority} · {detail.decision_number} · {detail.decision_date}</p><h4>错在哪里</h4><p>{detail.wrongdoing_summary}</p><h4>监管如何认定</h4><p>{detail.regulator_finding}</p><h4>制作公告时应检查</h4><ul>{detail.drafting_checks?.map(x=><li key={x}>{x}</li>)}</ul><h4>证据链</h4>{detail.evidence_documents?.map(d=><article className="blacklist-evidence" key={d.id}><Tag>{evidenceRoles[d.role]||d.role}</Tag><strong>{d.title}</strong><span>{d.published_at||''}</span><a href={`/api/library/items/${encodeURIComponent(detail.id)}/evidence/${encodeURIComponent(d.id)}?board=${board.layer}`} target="_blank" rel="noreferrer">查看保存原件</a><a href={d.url} target="_blank" rel="noreferrer">官方来源</a></article>)}{!detail.evidence_complete&&<p className="muted">涉事公告原件尚未完整关联；处理决定可读，但不能声称已完成公告逐项核对。</p>}<p className="muted">历史处理所依据的旧规则不能直接作为当前法源，制作时仍须核对法规库。</p></div>:detail.articles?<><p className="muted">{detail.title} · 共 {detail.articles.length} 条款。使用分页浏览条款，关闭窗口返回法规目录。</p><Table<Row> className="compact-library-table law-article-modal-table" rowKey="id" size="small" dataSource={detail.articles} scroll={{y:520,x:760}} pagination={{pageSize:20,showSizeChanger:false,showTotal:n=>`共 ${n} 条款`}} columns={[{title:'条款',dataIndex:'article',width:110,render:v=><span className="law-article-number">{v||'未编号'}</span>},{title:'法条正文',dataIndex:'text',render:v=><div className="law-article-text">{v||'未取得正文'}</div>}]}/></>:detail.sections?<>
 <p>{detail.applicability}</p><p><a href={`/api/library/template-file/${detail.id}?${new URLSearchParams({board:board.layer!,company:companyCode})}`} target="_blank" rel="noreferrer">下载当前 Word 模板</a></p><LibraryFileActions board={board.layer!} collection="profiles" company={companyCode} profileId={detail.id} onSaved={()=>setDetailRetry(x=>x+1)} onAssist={onAssist}/><Alert type="info" message="手工模板确认替换后成为当前版本；内容要求与版式适用性仍需核对。"/>
 {detail.sections.map(s=><details key={s.id} className="source-section"><summary>{s.title}</summary><p className="muted">{s.condition}</p>{s.requirement&&<p className="preserve">{s.requirement}</p>}{s.fields.map((f,i)=><div key={i}>{f.table_rows?<div style={{overflowX:'auto'}}><table className="profile-source-table"><tbody>{f.table_rows.map((row,j)=><tr key={j}>{row.map((cell,k)=><td key={k}>{cell||'—'}</td>)}</tr>)}</tbody></table></div>:<p className="preserve">{f.prompt}</p>}</div>)}</details>)}
 <details className="source-section"><summary>依据与案例</summary><h4>官方依据</h4>{detail.normative_sources?.map(r=><p key={r.id}><Button type="link" className="text-link" onClick={()=>{setDocumentPage(1);setSelected(r);}}>{r.title} · {r.article}</Button></p>)}<h4>结构对照案例</h4>{detail.case_sources?.map(r=><p key={r.id}><Button type="link" className="text-link" onClick={()=>{setDocumentPage(1);setSelected(r);}}>{r.title} · {r.published_at}</Button></p>)}</details><h4>起草时须核对</h4>{detail.semantic_review?.map((s,i)=><p key={i}>{s}</p>)}
 </>:<>
 {detail.source_kind==='imported_case_candidate'&&<Alert type="warning" message="导入文本尚未取得可核验的官方原件；只能作为待核验线索，不能作为已核实案例或法律依据。"/>}
 {detail.eligible_as_case_evidence===false&&detail.source_kind!=='imported_case_candidate'&&<Alert type="warning" message="此资料尚未核实公告时点所属层级，不计入本层案例，不能作为任务清单依据。"/>}
 {detail.source_kind==='official_case'&&<p className="muted">以下为按页提取文本，表格列关系及金额请结合原件核对。{detail.original_path&&<a href={`/api/library/assets/${encodeURIComponent(detail.id)}?board=${board.layer}`} target="_blank" rel="noreferrer"> 下载已登记原件</a>}</p>}
 {detail.text_completeness==='selected_visual_transcription'&&<Alert type="warning" message="扫描原件：这里仅展示已核对的结构及关键字段，完整内容请查看原件。"/>}
 <Evidence items={[{...detail,text:detail.document_path?(detail.pages?.map(p=>typeof p==='number'?'':p.text).join('\n')||detail.text):detail.text}]}/>
 {!!detail.page_count&&<Pagination simple current={documentPage} total={detail.page_count} pageSize={1} onChange={setDocumentPage}/>}
 {detail.original_path&&<p><a href={`/api/library/assets/${encodeURIComponent(detail.id)}?board=${board.layer}`} target="_blank" rel="noreferrer">下载已登记原件（校验哈希）</a></p>}
 </>}
 </Modal></section>;
}
