import {useEffect,useState} from 'react';
import {Alert,Button,Checkbox,Input,Modal,Select,Space} from 'antd';
import {api} from '../api';

type Prepared={id:string;filename:string;suggested_title:string;suggested_kind?:string;source_url:string;document:{pages:{page:number;text:string;page_label?:string}[];warnings:string[];needs_review:boolean;requires_ocr:boolean};fields:Record<string,unknown>};
type Pending=Prepared&{metadata:Record<string,string|boolean>;done?:boolean};
type Deletion={fingerprint:string;notice:string;objects:{id:string;title:string}[];references:{kind:string;title:string}[]};
const fileBytes=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('读取文件失败'));r.readAsDataURL(file);});

export default function LibraryFileActions({board,collection,company='',selected=[],profileId,onSaved,onAssist}:{board:string;collection:string;company?:string;selected?:string[];profileId?:string;onSaved:()=>void;onAssist?:(message:string)=>void}){
 const [open,setOpen]=useState(false),[files,setFiles]=useState<Pending[]>([]),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[deletion,setDeletion]=useState<Deletion>(),[replacement,setReplacement]=useState<{fingerprint:string;message:string;old_sha256:string;new_sha256:string}>();
 const scopeCompany=collection==='history'||collection==='profiles'?company:'';
 const [profiles,setProfiles]=useState<{id:string;title:string}[]>([]),[baseProfile,setBaseProfile]=useState('');
 useEffect(()=>{if(collection==='profiles'&&!profileId)api<{items:typeof profiles}>(`/library/profiles/manage?board=${board}&company=${company}`).then(r=>setProfiles(r.items)).catch(e=>setError(e.message));},[board,collection,profileId,company]);
 const receive=(p:Prepared)=>setFiles(prev=>[...prev,{...p,metadata:{title:p.suggested_title,kind:p.suggested_kind||'unclassified',url:p.source_url,published_at:'',effective_from:'',disposition_type:'administrative_penalty'}}]);
 const prepare=async(body:Record<string,string>)=>{const p=await api<Prepared>('/library/imports','POST',{board,collection,company:scopeCompany,...body});receive(p);};
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const set=(id:string,key:string,value:string|boolean)=>setFiles(prev=>prev.map(f=>f.id===id?{...f,metadata:{...f.metadata,[key]:value}}:f));
 return <><Space wrap><Button onClick={()=>{setOpen(true);setError('');setNotice('');}} disabled={collection==='history'&&!company}>{profileId?'上传替换模板':'新增入库'}</Button>{selected.length>0&&<Button danger loading={busy} onClick={()=>run(async()=>setDeletion(await api<Deletion>('/library/deletion-preview','POST',{board,collection,company:scopeCompany,ids:selected})))}>删除所选（{selected.length}）</Button>}</Space>{notice&&<p role="status">{notice}</p>}
 <Modal title={profileId?'上传手工修改后的模板':'新增资料入库'} open={open} width={900} onCancel={()=>{if(!busy)setOpen(false);}} footer={<Space><Button disabled={busy} onClick={()=>setOpen(false)}>关闭</Button><Button type="primary" loading={busy} disabled={!files.some(f=>!f.done)} onClick={()=>run(async()=>{
   if(profileId){const f=files.find(f=>!f.done)!;setReplacement(await api('/library/template-replacement','POST',{board,company:scopeCompany,profile_id:profileId,import_id:f.id}));return;}
   for(const f of files.filter(x=>!x.done)){const result:{index?:{status?:string}}=collection==='profiles'?await api<{index?:{status?:string}}>('/library/template-upload','POST',{board,company:scopeCompany,base_profile_id:baseProfile,import_id:f.id,title:f.metadata.title}):await api<{index?:{status?:string}}>(`/library/imports/${f.id}/commit`,'POST',{board,collection,company:scopeCompany,metadata:f.metadata});if(collection==='history'&&result.index?.status!=='current')throw new Error('原件已保存，但历史公告索引未完成；请检查索引状态后重试。');setFiles(prev=>prev.map(p=>p.id===f.id?{...p,done:true}:p));onSaved();}
   setNotice('本批资料已入库；来源与专业核验状态在列表中分别显示。');setOpen(false);
 })}>{profileId?'预览替换影响':'确认本批入库'}</Button></Space>}>
 <p>上传 PDF / DOCX，或提供官方文件链接。监管案例也支持官方 HTML 页面。原文件保持不变，自动提取正文；OCR、图片和修订内容需核对。</p>
 {collection==='profiles'&&!profileId&&<><p>选择沿用的公告文种与内容要求，新模板的手工文件保留不变。</p><Select aria-label="新模板参考文种" value={baseProfile||undefined} placeholder="选择参考文种" style={{width:'100%',marginBottom:12}} options={profiles.map(p=>({value:p.id,label:p.title}))} onChange={setBaseProfile}/></>}
 <input aria-label="上传资料文件" type="file" accept={collection==='profiles'?'.docx':collection==='blacklist_cases'?'.pdf,.docx,.html,.htm':'.pdf,.docx'} multiple={!profileId} disabled={busy} onChange={e=>{const chosen=Array.from(e.target.files||[]);e.target.value='';void run(async()=>{for(const file of chosen){if(file.size>30*1024*1024)throw new Error('单文件须小于30MB');await prepare({file_base64:await fileBytes(file),filename:file.name});}});}}/>
 {!profileId&&<Space.Compact style={{width:'100%',margin:'16px 0'}}><Input aria-label="官方文件链接" placeholder="官方 PDF / Word 文件链接" value={url} onChange={e=>setUrl(e.target.value)}/><Button loading={busy} onClick={()=>run(()=>prepare({url}))}>下载并抽取</Button></Space.Compact>}
 {busy&&<p role="status">正在处理文件，请保留此窗口；较长文件和 OCR 需要更多时间。</p>}
 {files.map(f=><article key={f.id} className="source-section"><h4>{f.filename} {f.done?'· 已入库':''}</h4>{!profileId&&<><Input aria-label={`标题 ${f.filename}`} value={String(f.metadata.title||'')} onChange={e=>set(f.id,'title',e.target.value)} placeholder="资料标题"/><Input aria-label={`发布来源 ${f.filename}`} value={String(f.metadata.url||'')} onChange={e=>set(f.id,'url',e.target.value)} placeholder="官方发布页面或文件链接" style={{marginTop:8}}/><Input aria-label={`日期 ${f.filename}`} type="date" value={String(f.metadata[collection==='laws'?'effective_from':'published_at']||'')} onChange={e=>set(f.id,collection==='laws'?'effective_from':'published_at',e.target.value)} style={{margin:'8px 0',width:190}}/>{collection==='laws'&&<span> 生效日期</span>}{collection==='blacklist_cases'&&<div className="blacklist-import-fields"><Space.Compact block><Input aria-label="上市公司名称" placeholder="上市公司名称" value={String(f.metadata.company_name||'')} onChange={e=>set(f.id,'company_name',e.target.value)}/><Input aria-label="证券代码" placeholder="证券代码" maxLength={6} value={String(f.metadata.stock_code||'')} onChange={e=>set(f.id,'stock_code',e.target.value)}/></Space.Compact><Space.Compact block><Input aria-label="处理机关" placeholder="处理机关" value={String(f.metadata.authority||'')} onChange={e=>set(f.id,'authority',e.target.value)}/><Input aria-label="决定编号" placeholder="决定编号" value={String(f.metadata.decision_number||'')} onChange={e=>set(f.id,'decision_number',e.target.value)}/><Select aria-label="处理性质" value={String(f.metadata.disposition_type||'administrative_penalty')} options={[{value:'administrative_penalty',label:'行政处罚'},{value:'disciplinary_action',label:'交易所纪律处分'},{value:'regulatory_measure',label:'监管措施'}]} onChange={v=>set(f.id,'disposition_type',v)}/></Space.Compact><Input aria-label="公告类型" placeholder="公告类型代码，多个用逗号分隔" value={String(f.metadata.announcement_kinds||'')} onChange={e=>set(f.id,'announcement_kinds',e.target.value)}/><Input aria-label="错误类型" placeholder="错误类型代码，多个用逗号分隔" value={String(f.metadata.violation_types||'')} onChange={e=>set(f.id,'violation_types',e.target.value)}/><Input.TextArea aria-label="错误摘要" placeholder="错在哪里" value={String(f.metadata.wrongdoing_summary||'')} onChange={e=>set(f.id,'wrongdoing_summary',e.target.value)} rows={2}/><Input.TextArea aria-label="监管认定" placeholder="监管如何认定" value={String(f.metadata.regulator_finding||'')} onChange={e=>set(f.id,'regulator_finding',e.target.value)} rows={2}/><Input aria-label="起草检查项" placeholder="制作公告时应检查什么，多个用逗号分隔" value={String(f.metadata.drafting_checks||'')} onChange={e=>set(f.id,'drafting_checks',e.target.value)}/><Alert type="info" message="首次入库进入待核线索；核实官方决定、违规时点创业板归属和关联公告后才能接纳。"/></div>}{collection==='history'&&<><Checkbox checked={f.metadata.publication_confirmed===true} onChange={e=>set(f.id,'publication_confirmed',e.target.checked)}>确认这是本公司已正式发布的公告</Checkbox><Checkbox checked={f.metadata.company_confirmed===true} onChange={e=>set(f.id,'company_confirmed',e.target.checked)}>已核对原件的公司归属</Checkbox></>}</>}
 {!!f.document.warnings.length&&<Alert type="warning" message={f.document.warnings.join('；')}/>}
 <details><summary>核对抽取正文（{f.document.pages.length} 个页或结构单元）</summary>{f.document.pages.map(p=><div key={p.page}><strong>{p.page_label||`第 ${p.page} 页`}</strong><pre className="preserve">{p.text||'未取得正文'}</pre></div>)}</details>
 {f.document.needs_review&&<Checkbox checked={f.metadata.extraction_confirmed===true} onChange={e=>set(f.id,'extraction_confirmed',e.target.checked)}>已结合原件核对 OCR、图片或修订部分</Checkbox>}
 {onAssist&&<Button type="link" onClick={()=>{onAssist(`请核对导入文件 ${f.id}，使用 knowledge_import_read 逐页读取，辅助识别资料类型、标题、日期和可定位字段；不要重写原件，也不要代替我确认发布或OCR准确性。`);setOpen(false);}}>交给 Pi 辅助核对</Button>}
 </article>)}{error&&<Alert type="error" message={error}/>}</Modal>
 <Modal title="确认删除资料" open={!!deletion} onCancel={()=>setDeletion(undefined)} confirmLoading={busy} okText="删除以上对象" okButtonProps={{danger:true}} onOk={()=>run(async()=>{await api('/library/delete','POST',{preview:deletion,fingerprint:deletion!.fingerprint});setDeletion(undefined);setNotice('已删除当前条目；必要历史引用与原件保留。');onSaved();})}><p>{deletion?.notice}</p><ul>{deletion?.objects.map(r=><li key={r.id}>{r.title}</li>)}</ul>{deletion?.references.map((r,i)=><p key={i}>{r.kind}：{r.title}</p>)}{error&&<Alert type="error" message={error}/>}</Modal>
 <Modal title="确认启用手工模板" open={!!replacement} onCancel={()=>setReplacement(undefined)} confirmLoading={busy} onOk={()=>run(async()=>{await api('/library/template-replacement','POST',{board,company:scopeCompany,profile_id:profileId,import_id:files.find(f=>!f.done)!.id,fingerprint:replacement!.fingerprint,apply:true});setReplacement(undefined);setOpen(false);setFiles([]);setNotice('已启用上传原文件作为当前模板，旧版保留。');onSaved();})}><p>{replacement?.message}</p><p>原版本：{replacement?.old_sha256.slice(0,12)}</p><p>新版本：{replacement?.new_sha256.slice(0,12)}</p>{error&&<Alert type="error" message={error}/>}</Modal>
 </>;
}
