import {useEffect,useState} from 'react';
import {Alert,Button,Checkbox,Empty,Input,InputNumber,Modal,Select,Spin,Switch} from 'antd';
import {PlusOutlined,PlusCircleOutlined,ReloadOutlined,SettingOutlined,DownOutlined,RightOutlined,InfoCircleOutlined,EyeInvisibleOutlined,BulbOutlined,WifiOutlined} from '@ant-design/icons';
import {api} from '../api';
import '../modelSettings.css';
import type {CatalogModel,LoginJob,ModelCatalog,ModelProfile,ModelSettingsSnapshot,ProviderSync} from '../modelSettings';
import {modelFields,profileLabel,routeLabels,groupProviders,providerFamily,authorizationRows,newModelProfile,profileFromCatalog,credentialSecretFields,modelDefaults,modelThinkingLevels as levels,modelApiOptions} from '../modelSettings';
import ModelLoginDialog from './ModelLoginDialog';
const googleBroker='nero-opencodex-loopback';
const providerCredentialNote='API Key 已按供应商保存到系统凭据库，该供应商的全部模型共用这一密钥。';
const syncMessage=(fallback:string,sync?:ProviderSync)=>{
 if(!sync)return fallback;
 if(sync.status==='failed')return `${fallback}云端模型同步未完成：${sync.reason||'接口未返回模型列表'}。可稍后点“同步云端模型”重试。`;
 if(sync.status==='synced')return `${fallback}已同步 ${sync.listed||0} 个模型，新增 ${sync.added||0} 个；默认选择保留。`;
 return `${fallback}供应商模型与本地配置一致（${sync.listed||0} 个）。`;
};
const accountAuth=(mode:string)=>['oauth','google_oauth'].includes(mode);
const emptyProfile=()=>newModelProfile('model-'+crypto.randomUUID().slice(0,8));
export default function ModelSettingsPage({onBack,backLabel='返回对话'}:{onBack:()=>void;backLabel?:string}){
 const [settings,setSettings]=useState<ModelSettingsSnapshot>(),[catalog,setCatalog]=useState<ModelCatalog>();
 const [routeDraft,setRouteDraft]=useState<Record<string,string>>(),[expanded,setExpanded]=useState<string[]>([]),[showProviders,setShowProviders]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [draft,setDraft]=useState<ModelProfile>(),[editKey,setEditKey]=useState(''),[custom,setCustom]=useState(false);
 const [apiKeys,setApiKeys]=useState<Record<string,string>>({}),[providerEnv,setProviderEnv]=useState<Record<string,Record<string,string>>>({}),[removing,setRemoving]=useState<ModelProfile>();
 const [credentialEditors,setCredentialEditors]=useState<string[]>([]);
 const [login,setLogin]=useState<LoginJob>();
 useEffect(()=>{let active=true;const id=sessionStorage.getItem('disclosure-model-login');if(id)api<LoginJob>(`/model-settings/login/${encodeURIComponent(id)}`).then(value=>active&&setLogin(value)).catch(()=>sessionStorage.removeItem('disclosure-model-login'));return()=>{active=false;};},[]);
 useEffect(()=>{if(login?.status==='waiting')sessionStorage.setItem('disclosure-model-login',login.id);else if(login)sessionStorage.removeItem('disclosure-model-login');},[login?.id,login?.status]);
 const accept=(value:ModelSettingsSnapshot)=>setSettings(value);
 const refresh=async()=>accept(await api<ModelSettingsSnapshot>('/model-settings'));
 useEffect(()=>{let ok=true;Promise.all([api<ModelSettingsSnapshot>('/model-settings'),api<ModelCatalog>('/model-settings/catalog')]).then(([s,c])=>{if(ok){accept(s);setCatalog(c);}}).catch(e=>ok&&setError(e.message));return()=>{ok=false;};},[]);
 useEffect(()=>{
  if(!login||login.status!=='waiting')return;let active=true;let timer:ReturnType<typeof setTimeout>;
  const read=async()=>{try{const result=await api<LoginJob>(`/model-settings/login/${login.id}`);if(!active)return;setLogin(result);if(result.status==='waiting')timer=setTimeout(read,1800);else if(result.status==='completed'){setMessage('供应商授权已保存，可以同步模型目录并测试连接。');await refresh();}}catch(e){if(active){setError((e as Error).message);timer=setTimeout(read,3000);}}};timer=setTimeout(read,700);
  return()=>{active=false;clearTimeout(timer);};
 },[login?.id,login?.status]);
 const act=async(name:string,fn:()=>Promise<void>)=>{setBusy(name);setError('');setMessage('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy('');}};
 const save=async(models:ModelProfile[],nextRoutes=settings?.routes||{})=>{
  if(!settings)return;accept(await api<ModelSettingsSnapshot>('/model-settings','PUT',{expected_revision:settings.revision,models:models.map(modelFields),routes:nextRoutes}));
 };
 const change=(row:ModelProfile,patch:Partial<ModelProfile>)=>act(row.key,async()=>{if(settings)await save(settings.models.map(m=>m.key===row.key?{...m,...patch}:m));});
 const beginEdit=(row?:ModelProfile)=>{setEditKey(row?.key||'');setDraft(row?modelFields(row):emptyProfile());setCustom(!!row&&!catalog?.providers.find(p=>p.id===row.provider)?.models.some(m=>m.id===row.id));};
 const beginProvider=(id:string)=>{const p=catalog?.providers.find(item=>item.id===id),first=p?.models[0];setEditKey('');setCustom(!first);setDraft(profileFromCatalog(emptyProfile(),id,first,p?.baseUrl));};
 const provider=catalog?.providers.find(p=>p.id===draft?.provider);
 const chooseCatalogModel=(value:CatalogModel)=>{if(draft)setDraft(profileFromCatalog(draft,draft.provider,value,provider?.baseUrl));};
 if(!settings)return <section className="model-settings-page">{error?<Alert type="error" message={error} action={<Button onClick={()=>act('reload',refresh)}>重新读取</Button>}/>:<Spin tip="正在读取模型设置"/>}</section>;
 const disabled=!!busy||!!settings.running,groups=groupProviders(settings.models,catalog),unconfiguredCount=groups.filter(group=>!group.registered).length;
 const visibleGroups=groups.filter(group=>group.registered||showProviders);
 const toggleGroup=(id:string)=>setExpanded(open=>open.includes(id)?open.filter(value=>value!==id):[...open,id]);
 const saveInlineKey=(row:ModelProfile)=>act('credential-'+row.key,async()=>{const result=await api<{sync?:ProviderSync}>(`/model-settings/${row.key}/credential`,'POST',{api_key:apiKeys[row.key]||'',...(Object.values(providerEnv[row.provider]||{}).some(Boolean)?{provider_env:providerEnv[row.provider]}:{})});setApiKeys(keys=>({...keys,[row.key]:''}));await refresh();setCredentialEditors(ids=>ids.filter(id=>id!==row.provider));setMessage(syncMessage(providerCredentialNote,result.sync));});
 const syncProvider=(id:string)=>act('sync-'+id,async()=>{const result=await api<{sync:ProviderSync;settings:ModelSettingsSnapshot}>(`/model-settings/providers/${id}/sync`,'POST',{expected_revision:settings?.revision});accept(result.settings);setMessage(syncMessage('',result.sync));});
 const testConnection=(row:ModelProfile)=>act('test-'+row.key,async()=>{const result=await api<{status:string;message?:string}>(`/model-settings/${row.key}/test`,'POST',{});await refresh();if(result.status==='passed')setMessage(`${profileLabel(row)} 连接测试通过。`);else setError(result.message||'模型连接未通过');});
 return <section className="model-settings-page banker-model-settings">
  <div className="page-heading"><div><h1>模型与供应商</h1><p className="muted">配置授权、可用模型与聊天栏显示范围</p></div><Button type="text" onClick={onBack}>{backLabel}</Button></div>
  {settings.running&&<Alert type="info" message="当前有模型执行，待本轮结束后可修改配置。"/>}
  <div className="provider-catalog-toolbar"><Button type="text" icon={showProviders?<EyeInvisibleOutlined/>:<PlusCircleOutlined/>} disabled={disabled||!unconfiguredCount&&!showProviders} aria-label={showProviders?'隐藏未配置供应商':`添加其他供应商（${unconfiguredCount}）`} aria-expanded={showProviders} onClick={()=>setShowProviders(!showProviders)}>{showProviders?'隐藏未配置供应商':`添加其他供应商（${unconfiguredCount}）`}</Button></div>
  <section className="provider-list" aria-label="模型供应商">
   {!visibleGroups.length&&<Empty description="点击上方添加供应商，再配置模型与授权"/>}
   {visibleGroups.map(group=>{const open=expanded.includes(group.id),routed=group.models.some(row=>Object.values(settings.routes).includes(row.key)),allEnabled=group.models.length>0&&group.models.every(row=>row.enabled),someEnabled=group.models.some(row=>row.enabled);
    const authRows=authorizationRows(group.models);
    return <section className="provider-panel" key={group.id} aria-label={group.name} data-provider-family={group.id}>
     <div className="provider-heading"><button className="provider-disclosure" aria-label={`${group.name} 授权与模型`} aria-expanded={open} aria-controls={'provider-'+group.id} onClick={()=>toggleGroup(group.id)}><span className="model-provider-symbol" aria-hidden="true">{group.id==='gpt'?<BulbOutlined/>:group.id==='deepseek'?<WifiOutlined/>:<SettingOutlined/>}</span><span className="provider-title"><strong>{group.name}</strong><small className={group.authorized?'provider-authorized':''}>{group.authorization}{group.registered&&!someEnabled?' · 已停用':''}</small></span></button><Checkbox aria-label={`启用供应商 ${group.name}`} title={routed?'先调整正在使用该供应商的默认模型，再停用':group.registered?`启用或停用 ${group.name} 的全部模型`:'先展开并添加模型，再启用供应商'} checked={allEnabled} indeterminate={someEnabled&&!allEnabled} disabled={disabled||routed||!group.registered} onChange={e=>act('provider-'+group.id,async()=>{await save(settings.models.map(row=>group.providerIds.includes(row.provider)?{...row,enabled:e.target.checked}:row));})}/><Button type="text" className="provider-expand-button" aria-label={`${open?'收起':'展开'} ${group.name}`} aria-expanded={open} aria-controls={'provider-'+group.id} icon={open?<DownOutlined/>:<RightOutlined/>} onClick={()=>toggleGroup(group.id)}/></div>
     {open&&<div id={'provider-'+group.id} className="provider-content">
      {!!group.models.length&&<><div className="provider-columns" aria-hidden="true"><span>模型</span><span>聊天栏显示</span><span>默认</span><span>状态</span><span/></div>
      {group.models.map(row=>{const check=settings.checks[row.key],selected=settings.routes.default===row.key,checkLabel=check?check.status==='passed'?'连接已通过':check.status==='stale'?'请重新测试':'连接未通过':'尚未测试连接';return <article className="model-profile-row compact-model-row" key={row.key} data-model-key={row.key}>
       <div className="compact-model-name"><h3 title={`${profileLabel(row)} · ${row.id}`}>{profileLabel(row)}{group.providerIds.length>1&&<small>{row.auth_type==='google_oauth'?'Google 授权':row.auth_type==='oauth'?'ChatGPT':'API'}</small>}</h3></div>
       <div className="model-cell"><span className="model-mobile-label">聊天栏显示</span><Checkbox aria-label={`在聊天栏显示 ${row.label}`} checked={row.visible} disabled={disabled} onChange={e=>change(row,{visible:e.target.checked})}/></div>
       <div className="model-cell"><span className="model-mobile-label">默认模型</span><button className={'model-default-choice'+(selected?' selected':'')} aria-label={`设为默认模型 ${row.label}`} aria-pressed={selected} title={selected?'当前默认模型':row.configured?'设为默认模型':'完成授权并启用后可选为默认模型'} disabled={disabled||!row.configured} onClick={()=>act('default-'+row.key,async()=>{await save(settings.models.map(model=>model.key===row.key?{...model,visible:true}:model),{...settings.routes,default:row.key});setMessage(`${profileLabel(row)} 已设为默认模型，下一次准备执行时生效。`);})}><span/></button></div>
       <div className="model-connection"><Button type="text" size="small" aria-label={`测试连接 ${row.label}`} title={row.configured?check?.status==='passed'?`上次通过：${new Date(check.at*1000).toLocaleString('zh-CN')}。点击重新测试。`:'发送固定短消息测试连接，可能消耗账户额度':row.reason} disabled={disabled||!row.configured} loading={busy==='test-'+row.key} onClick={()=>testConnection(row)}><span className={'connection-dot '+(row.configured&&check?.status==='passed'?'ready':'')}/>{!row.enabled?'已停用':!row.configured?'待配置':busy==='test-'+row.key?'测试中':check?.status==='failed'?'重新测试':'测试连接'}</Button><span className="model-check-detail">{checkLabel}</span></div>
       <Button type="text" className="model-edit-button" size="small" icon={<SettingOutlined/>} aria-label={`编辑模型 ${row.label}`} disabled={disabled} onClick={()=>beginEdit(row)}/>
      </article>;})}</>}
      <div className="provider-authorization" aria-label={`${group.name} 授权`}>
       {group.id==='gemini'&&<div className="provider-auth-row" data-auth-type="google_oauth"><div className="provider-auth-description"><strong>Google / agy 账号授权</strong><span className={settings.gemini_broker?.status==='delegated_unverified'?'model-status-ready':'model-status-pending'}>{settings.gemini_broker?.message||'复用 NERO Banker 的现有授权，添加 Gemini 3.8、3.7'}</span></div><div className="provider-auth-actions"><Button size="small" type={settings.gemini_broker?'default':'primary'} disabled={disabled} loading={busy==='gemini-connect'} onClick={()=>act('gemini-connect',async()=>{const result=await api<ModelSettingsSnapshot>('/model-settings/gemini/connect','POST',{expected_revision:settings.revision});accept(result);if(result.gemini_broker?.status==='unavailable')setError(result.gemini_broker.message);else setMessage('Gemini 3.8、3.7 已连接 Banker 共用通道，可以分别测试连接。');})}>{settings.gemini_broker?'检查已有授权':'连接 Banker 已有授权'}</Button></div></div>}
       {authRows.map(row=><div className={'provider-auth-row '+(row.auth_type==='api_key'?'provider-api-key-row':'')} key={row.key} data-auth-model={row.key}><div className="provider-auth-description"><strong>{row.auth_type==='oauth'?'ChatGPT 账号授权':row.auth_type==='api_key'?`${catalog?.providers.find(p=>p.id===row.provider)?.name||group.name} API Key`:row.auth_type==='local'?'本机服务':'环境变量授权'}</strong><span className={row.credential_configured?'model-status-ready':'model-status-pending'}>{row.credential_configured?'授权已配置':row.reason}</span></div><div className="provider-auth-actions">
        {row.auth_type==='api_key'&&row.credential_configured&&<Button type="text" size="small" disabled={disabled} onClick={()=>setCredentialEditors(ids=>ids.includes(row.provider)?ids.filter(id=>id!==row.provider):[...ids,row.provider])}>{credentialEditors.includes(row.provider)?'收起授权管理':'管理授权'}</Button>}
        {(row.auth_type!=='api_key'||!row.credential_configured||credentialEditors.includes(row.provider))&&<>
        {row.auth_type==='api_key'&&<>{(catalog?.providers.find(p=>p.id===row.provider)?.credential_fields||[]).map(field=><Input className="provider-credential-field" type={credentialSecretFields.includes(field)?'password':'text'} key={field} aria-label={`${row.provider} ${field}`} placeholder={field==='CLOUDFLARE_ACCOUNT_ID'?'Cloudflare 账号 ID':field==='CLOUDFLARE_GATEWAY_ID'?'Cloudflare 网关 ID':field} autoComplete="off" value={providerEnv[row.provider]?.[field]||''} onChange={e=>setProviderEnv(current=>({...current,[row.provider]:{...current[row.provider],[field]:e.target.value}}))} disabled={disabled}/>) }<Input.Password aria-label={`模型 API Key ${row.label}`} placeholder={row.credential_configured?'输入新的 API Key 以更新':`输入 ${group.name} API Key`} autoComplete="new-password" value={apiKeys[row.key]||''} onChange={e=>setApiKeys(keys=>({...keys,[row.key]:e.target.value}))} visibilityToggle={false} disabled={disabled||!settings.vault.available}/><Button aria-label={`保存 API Key ${row.label}`} size="small" type="primary" disabled={disabled||!settings.vault.available||((apiKeys[row.key]||'').trim().length<8&&!['amazon-bedrock','google-vertex'].includes(row.provider))} loading={busy==='credential-'+row.key} onClick={()=>saveInlineKey(row)}>{row.credential_configured?'更新密钥':'保存密钥'}</Button></>}
        {row.auth_type==='oauth'&&<Button size="small" type={row.credential_configured?'default':'primary'} disabled={disabled||!settings.vault.available||login?.status==='waiting'} onClick={()=>act('login',async()=>setLogin(await api<LoginJob>(`/model-settings/${row.key}/login`,'POST',{})))}>{row.credential_configured?'重新登录账号':row.provider==='openai-codex'?'登录 ChatGPT':'登录供应商账号'}</Button>}
        {row.credential_configured&&['api_key','oauth'].includes(row.auth_type)&&<Button size="small" type="text" disabled={disabled} onClick={()=>setRemoving(row)}>移除授权</Button>}
       </>}</div></div>)}
       <div className="provider-add-model">{group.catalogProviders.filter(p=>p.auth_types.includes('oauth')&&!group.models.some(m=>m.provider===p.id&&m.auth_type==='oauth')).map(p=><Button key={'login-'+p.id} size="small" disabled={disabled} onClick={()=>act('login',async()=>setLogin(await api<LoginJob>(`/model-settings/providers/${p.id}/login`,'POST',{})))}>登录 {p.name} 账号</Button>)}{group.catalogProviders.length?group.catalogProviders.map(p=>p.models.length?<Button key={p.id} type="text" size="small" icon={<PlusOutlined/>} disabled={disabled} onClick={()=>beginProvider(p.id)}>{group.providerIds.length>1?`添加${p.id===googleBroker?' Google 授权 ':p.id==='openai-codex'?' ChatGPT ':p.id==='openai'?' API Key ':` ${p.name} `}模型`:'添加模型'}</Button>:<span key={p.id} className="provider-unsupported">{`${p.name}：尚无目录模型，可同步云端模型。`}</span>):<Button type="text" size="small" icon={<PlusOutlined/>} disabled={disabled} onClick={()=>beginProvider(group.providerIds[0])}>添加模型</Button>}{group.catalogProviders.filter(p=>p.auth_types.some(t=>['api_key','oauth'].includes(t))).map(p=><Button key={'sync-'+p.id} type="text" size="small" icon={<ReloadOutlined/>} disabled={disabled} loading={busy==='sync-'+p.id} onClick={()=>syncProvider(p.id)}>{group.providerIds.length>1?`同步 ${p.name} 云端模型`:'同步云端模型'}</Button>)}</div>
      </div>
     </div>}
    </section>;
   })}
  </section>
  <div className="provider-catalog-footer"><p><InfoCircleOutlined aria-hidden="true"/>供应商模型自动同步，默认模型由您选择。</p><Button aria-label="刷新模型目录" icon={<ReloadOutlined/>} loading={busy==='catalog'} disabled={!!busy} onClick={()=>act('catalog',async()=>{setCatalog(await api<ModelCatalog>('/model-settings/catalog/refresh','POST',{}));await refresh();setMessage('模型目录已刷新。');})}>刷新模型目录</Button></div>
  {error&&<Alert type="error" message={error} closable onClose={()=>setError('')}/>}{message&&<Alert type="success" message={message} closable onClose={()=>setMessage('')}/>}
  <details className="model-advanced-settings"><summary>高级设置</summary><div className="model-advanced-actions"><Button aria-label="添加模型" disabled={disabled} onClick={()=>beginEdit()}>添加自定义模型</Button><Button disabled={disabled} onClick={()=>setRouteDraft({...settings.routes})}>按工作环节设置</Button></div><p>供应商列表直接来自当前 Pi 运行时内置目录。API Key 按供应商保存，同一供应商的模型共用一份密钥；保存密钥后会读取该账号可用的云端模型并合并到本地配置，已有模型设置与默认选择保持不变。ChatGPT 授权由本项目的 ChatGPT 模型共用。Google / agy 授权与 NERO Banker 共用本机 OpenCodex 服务，凭据由该服务管理。</p><p>配置授权与连接测试通过是两个独立状态。连接测试发送固定短消息，可能消耗账户额度，不发送事项、底稿或对话历史。</p><p>所有板块共用模型配置。默认选择在下一次准备执行时生效，发送前仍可切换；失败时不自动改用其他模型。当前 Pi {settings.pi_version}，刷新目录不会升级运行时。</p></details>
  <Modal className="model-settings-dialog" title="工作环节默认模型" open={!!routeDraft} width={640} okText="保存默认选择" confirmLoading={busy==='routes'} onCancel={()=>!busy&&setRouteDraft(undefined)} onOk={()=>act('routes',async()=>{if(!routeDraft)return;await save(settings.models,routeDraft);setRouteDraft(undefined);setMessage('工作环节默认模型已保存，下一次准备执行时生效。');})} okButtonProps={{'aria-label':'保存默认选择',disabled:disabled||JSON.stringify(routeDraft)===JSON.stringify(settings.routes)}}>
   {error&&<Alert type="error" message={error}/>}<p className="muted">单独指定的环节优先使用这里的模型；选择“沿用默认模型”可恢复统一设置。</p><div className="model-route-fields">{routeDraft&&Object.entries(routeLabels).map(([key,label])=><label key={key}><span>{label}</span><Select aria-label={`${label}模型`} value={routeDraft[key]||''} disabled={disabled} onChange={value=>setRouteDraft({...routeDraft,[key]:value})} options={[{value:'',label:key==='default'?'发送前选择':'沿用默认模型'},...settings.models.filter(row=>row.enabled).map(row=>({value:row.key,label:profileLabel(row)+(row.configured?'':'（待授权）')}))]}/></label>)}</div>
  </Modal>
  <Modal className="model-settings-dialog" title={editKey?'编辑模型配置':'添加模型'} open={!!draft} width={680} onCancel={()=>!busy&&setDraft(undefined)} okText="保存模型配置" confirmLoading={busy==='save'} onOk={()=>act('save',async()=>{if(!draft)return;await save(editKey?settings.models.map(row=>row.key===editKey?draft:row):[...settings.models,draft]);setExpanded(ids=>{const family=providerFamily(draft.provider);return ids.includes(family)?ids:[...ids,family];});setDraft(undefined);setMessage('模型配置已保存，请完成授权并测试连接。');})} okButtonProps={{'aria-label':'保存模型配置',disabled:disabled||!draft?.id.trim()||!draft?.label.trim()}}>
   {error&&<Alert type="error" message={error}/>}
   {draft&&<div className="model-form"><label><span>供应商</span><Select aria-label="模型供应商" showSearch optionFilterProp="label" value={provider?draft.provider:'custom'} onChange={id=>{const p=catalog?.providers.find(item=>item.id===id);const first=p?.models[0];setCustom(!p);setDraft({...profileFromCatalog({...emptyProfile(),key:draft.key,enabled:draft.enabled,visible:draft.visible},p?.id||'custom',first,p?.baseUrl),source:p?'pi_builtin':'custom'});}} options={[...(catalog?.providers.map(p=>({value:p.id,label:p.name}))||[]),{value:'custom',label:'自定义兼容接口'}]}/></label>
    {provider&&<><Checkbox disabled={draft.provider===googleBroker} checked={custom} onChange={e=>setCustom(e.target.checked)}>手动填写模型 ID</Checkbox>{!custom&&<label><span>{draft.provider===googleBroker?'Banker 共用模型':'Pi 内置模型'}</span><Select aria-label="Pi 内置模型" showSearch optionFilterProp="label" value={draft.id} onChange={id=>{const found=provider.models.find(m=>m.id===id);if(found)chooseCatalogModel(found);}} options={provider.models.map(m=>({value:m.id,label:m.label}))}/></label>}</>}
    <label><span>显示名称</span><Input aria-label="模型显示名称" value={draft.label} maxLength={100} onChange={e=>setDraft({...draft,label:e.target.value})}/></label>
    <label><span>模型 ID</span><Input aria-label="模型 ID" value={draft.id} disabled={!!provider&&!custom} onChange={e=>setDraft({...draft,id:e.target.value,source:'custom'})}/></label>
    <label><span>本模型默认档位</span><Select aria-label="模型推理档位" value={draft.reasoning_effort} onChange={reasoning_effort=>setDraft({...draft,reasoning_effort})} options={draft.thinking_levels.map(value=>({value,label:value==='off'?'不启用推理档位':value}))}/></label>
    <label className="model-enable-field"><span>启用此模型</span><Switch aria-label="启用此模型" checked={draft.enabled} disabled={!!editKey&&Object.values(settings.routes).includes(editKey)} onChange={enabled=>setDraft({...draft,enabled})}/>{!!editKey&&Object.values(settings.routes).includes(editKey)&&<small>此模型已用于默认选择，调整默认选择后可停用。</small>}</label>
    <details className="model-advanced-fields" key={editKey||'new'} open={custom||undefined}><summary>连接与高级参数</summary><div className="model-form">    <label><span>接口协议</span><Select aria-label="模型接口协议" value={draft.api} disabled={accountAuth(draft.auth_type)} onChange={api=>setDraft({...draft,api})} options={modelApiOptions}/></label>
    <label><span>接口地址</span><Input aria-label="模型接口地址" value={draft.baseUrl} disabled={accountAuth(draft.auth_type)} onChange={e=>setDraft({...draft,baseUrl:e.target.value})}/></label>
    {draft.auth_type!=='google_oauth'&&<label><span>授权方式</span><Select aria-label="模型授权方式" value={draft.auth_type} onChange={auth_type=>setDraft({...draft,auth_type})} options={[...(provider?.auth_types.includes('oauth')?[{value:'oauth',label:'供应商账号登录'}]:[]),...(draft.provider==='openai-codex'?[]:[{value:'api_key',label:'API Key / 云凭据 · 系统凭据库'},{value:'environment',label:'专用环境变量'},{value:'local',label:'本机服务（无独立密钥）'}])]}/></label>}
    {draft.auth_type==='environment'&&<label><span>专用环境变量名</span><Input aria-label="模型凭据环境变量" value={draft.api_key_env} placeholder="DISCLOSURE_PROVIDER_API_KEY" onChange={e=>setDraft({...draft,api_key_env:e.target.value})}/></label>}
    <div className="model-form-grid"><label><span>上下文容量</span><InputNumber aria-label="模型上下文容量" value={draft.contextWindow} min={1} onChange={value=>setDraft({...draft,contextWindow:value||modelDefaults.contextWindow})}/></label><label><span>单轮输出上限</span><InputNumber aria-label="模型输出上限" value={draft.maxTokens} min={1} onChange={value=>setDraft({...draft,maxTokens:value||modelDefaults.maxTokens})}/></label></div>
    {custom&&<label><span>已核实的推理档位</span><Select mode="multiple" aria-label="模型支持档位" value={draft.thinking_levels} onChange={thinking_levels=>setDraft({...draft,thinking_levels,thinking_level_map:{},reasoning_effort:thinking_levels.includes(draft.reasoning_effort)?draft.reasoning_effort:thinking_levels[0]||'off'})} options={levels.map(value=>({value,label:value}))}/></label>}
</div></details>
   </div>}
  </Modal>
  <Modal className="model-settings-dialog" title="移除本项目模型授权" open={!!removing} okText="移除授权" okButtonProps={{danger:true}} confirmLoading={busy==='remove'} onCancel={()=>!busy&&setRemoving(undefined)} onOk={()=>act('remove',async()=>{if(!removing)return;await api(`/model-settings/${removing.key}/credential`,'DELETE');setRemoving(undefined);await refresh();})}><p>移除 {removing?.label} 的授权后，需要重新授权才能使用。ChatGPT 登录由本项目所有 ChatGPT 模型共用。</p></Modal>
  <ModelLoginDialog login={login} busy={!!busy} error={error} onClose={()=>setLogin(undefined)} onCancel={()=>login&&act('cancel-login',async()=>setLogin(await api<LoginJob>(`/model-settings/login/${login.id}`,'DELETE')))} onAnswer={value=>login&&act('login-answer',async()=>setLogin(await api<LoginJob>(`/model-settings/login/${login.id}/answer`,'POST',{prompt_id:login.prompt_id,value})))}/>
 </section>;
}
