export interface Field { key:string; label:string; type:string; required:boolean; options?: (string | {label:string;value:string})[]; help?:string }
export interface Meta { title:string;mode:string;mode_label?:string;producer?:{name:string;label?:string;product?:string;version?:string};scope_notice:string; companies:{id:string;name:string;layer:string}[];event_types:{id:string;label:string;fields:Field[]}[] }
export interface Knowledge { id:string;title:string;article:string;text:string;url:string;source_kind:string;effective_from?:string;effective_to?:string;as_of:string;limitations?:string|string[];eligible_as_case_evidence?:boolean;board_applicability?:{board:string;status:string;note:string} }
export interface PlanItem {id:string;title:string;requirement:string;detail:string;evidence_status:string;source_ids:string[];notes:string}
export interface DisclosureEvent {workflow_policy?:string;stock_code?:string;intake_mode?:string;output_mode?:'text'|'word';approval_records?:ApprovalRecord[];current_artifact_id?:string;escalation?:{node:string;reason:string};template?:{template_id:string;requirement_map:Record<string,string>;adaptations:string[]};verified_stages?:Record<string,Gate>;law_bindings?:Record<string,string>;artifacts?:Artifact[];source_search?:{status:string;message:string};agent_tasks?:AgentTask[];id:string;title:string;company_id:string;company_name:string;layer:string;kind:string;summary:string;facts:Record<string,unknown>;revision:number;stage:string;created_at:string;updated_at:string;assessment:null|{preliminary_plan?:PlanningView|null;facts?:{key:string;value:unknown;status:string;source_ref:string;quote:string;observed_at:string}[];matters?:MatterView[];id:string;status:string;summary:string;reasons:string[];missing:string[];citations:Knowledge[];calculations:{label:string;expression:string;result:unknown}[];limitations:string[];mode:string;producer?:{agent_name:string;host_family:string;task_id:string}};plan:null|{documents?:DocumentView[];requirements?:RequirementView[];drafting_gaps?:GapView[];profile_id?:string;id:string;items:PlanItem[];cases:Knowledge[];};draft:null|{id:string;template_id?:string;documents?:TextDocument[];text:string;checks:{label:string;status:string;detail:string}[]};audit:{at:string;actor:string;channel:string;action:string;revision:number;detail:unknown}[]}

export interface TextDocument {document_id:string;text:string;requirement_map:Record<string,string|string[]>}
export interface AgentTask {candidate_sources?:Knowledge[];id:string;stage:string;status:string;instruction:string;input_revision:number;input_fingerprint:string;created_at:number;status_reason:string;owner_name?:string;host_family?:string;host_run_ref?:string;lease_until?:number;result?:{preliminary_plan?:PlanningView|null;status?:string;summary?:string;reasons?:string[];missing?:string[];source_ids?:string[];limitations?:string[];items?:PlanItem[];template_id?:string;text?:string;documents?:TextDocument[]}|null}

export interface Gate {warnings?:{code:string;detail:string}[];semantic_review?:{code:string;detail:string}[];review_readiness?:string;drafting_readiness?:{status:string;blockers:string[]};status:'PASS'|'BLOCKED'|'PENDING_REVIEW';stage:string;input_fingerprint:string;issues:{code:string;detail:string;source_id?:string}[];next_action:{action:string};boundary:string}
export interface Artifact {id:string;filename:string;sha256:string;input_fingerprint:string;verification:{status:string};host_qa?:string}

export const stages:Record<string,string>={intake:'待分析',assessed:'判断候选',planned:'清单候选',drafted:'文稿候选',assessment_verified:'判断 Gate 通过',plan_verified:'清单 Gate 通过',draft_verified:'文稿 Gate 通过',delivered:'交付物已登记',closed:'事项已关闭',needs_reassessment:'输入变化，待重评',accepted:'历史记录，待新 Gate 检查'};

export interface ApprovalRecord {id:string;node:string;state:string;input_fingerprint:string;reviewer:string;reason:string;invalidation_reason?:string}
export interface MatterView {matter_id:string;subject:string;stage:string;duty_status:string;timing_status:string;trigger_events:string[];procedural_requirements:string[];decisive_questions:string[];reassessment_conditions:string[];limitations?:string[];reasoning_items:{condition:string;application:string;locator:string;quote:string}[]}
export interface DocumentView {purpose:string;stage:string;dependencies?:string[];document_id:string;title:string;producer:string;applicability:string;timing:string}
export interface RequirementView {applicability_status?:'applicable'|'not_applicable'|'unknown';document_id?:string;requirement_id:string;topic:string;granularity:string;applicability:string;verify_method:string}
export interface GapView {key:string;description:string;impact:string;treatment:string;owner:string}
Object.assign(stages,{awaiting_draft_confirmation:'待完整正文确认',text_confirmed:'正文已确认定稿',awaiting_assessment_information:'判断待补事实',text_draft_ready:'正文已核验（未制作 Word）',awaiting_assessment_confirmation:'待判断确认',awaiting_plan_confirmation:'待规划确认',awaiting_template_confirmation:'待模板确认',awaiting_word_confirmation:'待 Word 确认',planning:'规划中',selecting_template:'模板选择中',drafting:'制稿中',manual_escalation:'人工升级处理',specialist_handling:'专项处理中',no_disclosure_manual_tracking:'当前不披露，需人工跟踪',confirmed_draft_archived:'人工确认稿已归档（未公开）',plan_revision_required:'规划待修订',template_revision_required:'模板待修订',draft_revision_required:'正文待修订'});

export interface PlanningView {documents:DocumentView[];requirements:RequirementView[];drafting_gaps?:GapView[];blocking_questions?:string[];limitations?:string[]}
