import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import assert from 'node:assert/strict';
import MessageMarkdown from '../frontend/src/components/MessageMarkdown';
import RoundAnalysis from '../frontend/src/components/RoundAnalysis';
import {roundResult} from '../frontend/src/roundResult';
import type {Receipt} from '../frontend/src/chat';
const md=renderToStaticMarkup(<MessageMarkdown text={'**结论**：需要判断。\n\n| 文件 | 内容 |\n| --- | --- |\n| 公告甲 | 日期与数量 |\n\n<script>alert(1)</script>\n\n[危险](javascript:alert(1))\n\n![跟踪](https://example.invalid/pixel)'}/>);
assert.match(md,/<strong>结论<\/strong>/);assert.match(md,/<table>/);assert.doesNotMatch(md,/<script|javascript:|<img/);
const row=(seq:number,kind:string,body:object)=>({seq,kind,body,run_id:'one',at:0} as Receipt);
const one=[row(1,'result_snapshot',{event_id:'e',revision:7,stage:'assessment',outcome:'waiting_approval',result:{summary:'旧版本结论',missing:['日期待补']},sources:[]})];
const two=[row(2,'result_snapshot',{event_id:'e',revision:10,stage:'assessment',outcome:'waiting_approval',result:{summary:'新版本结论'},sources:[]})];
assert.equal(roundResult(one)?.revision,7);assert.equal(roundResult(two)?.revision,10);
const old=renderToStaticMarkup(<RoundAnalysis snapshot={roundResult(one)!} hasAnswer={false}/>);
assert.match(old,/旧版本结论/);assert.doesNotMatch(old,/新版本结论/);assert.match(old,/日期待补/);
const summarized=renderToStaticMarkup(<RoundAnalysis snapshot={roundResult(one)!} hasAnswer/>);
assert.match(summarized,/<details><summary>展开已登记的完整分析/);
const legacy=[row(1,'accepted',{stage:'assessment'}),row(2,'model_tool_call',{name:'submit_candidate',args:{result:{summary:'历史候选'}}}),row(3,'tool_returned',{name:'task.evaluate',result:{event_id:'e',expected_revision:4,outcome:'waiting_approval'}})];
assert.equal(roundResult(legacy)?.result?.summary,'历史候选');assert.equal(roundResult(legacy)?.revision,4);
const draft=renderToStaticMarkup(<RoundAnalysis snapshot={{event_id:'e',revision:11,stage:'draft',outcome:'completed',sources:[],result:{documents:[{document_id:'d',text:'正式文稿测试文本'}] as never}}} hasAnswer={false}/>);
assert.match(draft,/正式文稿测试文本/);assert.doesNotMatch(draft,/文件与用途/);
console.log(JSON.stringify({status:'PASS',checks:['Markdown段落和表格','不执行HTML及危险链接或远程图片','两轮历史不串版','原始内容按需展开且保留缺口','旧流水只读兼容','正文按文稿呈现']},null,2));
