export type Law={instrument_id:string;title:string;article_count:number;status:string;validity?:string;last_checked_at?:string;last_result?:string;url?:string;validity_evidence?:{url:string;quote:string}};
export type Laws={records:Law[];generated_at:string};
export type Model={key:string;label:string;configured:boolean;enabled:boolean;visible?:boolean};
export type Backup={path:string;bytes:number;mtime_ns:number;eligible:boolean;reason:string};
export type Database={id:string;label:string;kind:string;current_path:string;current_bytes:number;sidecar_bytes:number;backups:Backup[];backup_count:number;needs_attention:boolean;reclaimable_bytes:number};
export type Cache={id:string;label:string;count:number;bytes:number};
export type Action={id:string;at:string;status:string;category:string;released_bytes:number;count:number};
export type Quarantine={id:string;count:number;bytes:number;entries:{path:string;bytes:number}[]};
export type Inventory={scanned_at:string;disk:{free:number;total:number};notice:string;review_interval_days:number;
 databases:{groups:Database[];unclassified:Backup[];retention:number;excess_groups:number};caches:{groups:Cache[];bytes:number;count:number;notice:string};history:Action[];quarantine?:{items:Quarantine[];count:number;bytes:number;notice:string}};
export type Preview={id:string;category:string;bytes:number;count:number;notice:string;entries:Backup[]};
export type Batch={batch_id:string;status:string;total:number;completed:number;session_id:string;active_run_id?:string;error?:string;coverage_articles:number;items:{instrument_id:string;title:string;status:string;run_id?:string;validity:string;detail:string}[]};
export type HealthRun={run_id:string;session_id:string;session_title:string;event_id:string;board:string;stage:string;stage_name:string;status:string;status_name:string;outcome:string;reason:string;provider_error:string;model:string;updated_iso:string;age_seconds?:number;live:boolean;is_current?:boolean;gate_status:string;gate_scope?:string;blockers:string[];next_step:string};
export type HealthTask={event_id:string;event_title:string;company_name:string;event_revision:number;task_id:string;stage:string;stage_name:string;status:string;status_reason:string;age_seconds?:number;outcome:string;gate_status:string;escalation:boolean;instruction:string};
export type Finding={level:string;code:string;message:string;action:string;detail?:string;ids?:string[]};
export type Health={scanned_at:string;boundary:string;elapsed_ms:number;
 service:{pid:number;started_at:string;uptime_seconds:number;python:string;platform:string;directory:string;project_root:string;port?:number;entry:string};
 engine:{name:string;version:string;installed:boolean;node:string;worker:string;worker_present:boolean;core_present:boolean;configuration_path:string;settings_revision:number;default_route:string;models:{total:number;configured:number;enabled:number};active_rounds:number;closed:boolean;error?:string|null};
 storage:{databases:{path:string;name:string;exists:boolean;bytes:number;wal_bytes:number;readable:boolean;quick_check:string|null;missing_tables:string[];counts:Record<string,number>;error?:string|null;elapsed_ms:number}[];disk:{free:number;total:number}};
 runs:{rows:HealthRun[];counts:Record<string,number>;total:number;live:HealthRun[];attention:HealthRun[]};
 tasks:{hanging:HealthTask[];active_count?:number;escalated:{event_id:string;event_title:string;company_name:string;event_stage:string;node:string;reason:string;event_revision:number}[]};
 findings:Finding[]};
